#cloud-config
  #local-hostname: ${name}
  #instance-id: ubuntu-${name}
  #network:
  #  version: 2
  #  ethernets:
  #    ens192:
  #      dhcp4: false
  #      addresses:
  #        - ${ipv4_address}/24
  #      gateway4: ${ipv4_gateway}
  #      nameservers:
  #        search: [home]
  #        addresses: [${dns_server_1}]
  #wait-on-network:
  #ipv4: true
