#cloud-config
network:
  version: 2
  ethernets:
    ens160:
      dhcp4: false
      addresses:
        - ${ipv4_address}/24
      gateway4: 10.10.69.1
      nameservers:
          addresses: [8.8.8.8, 8.8.4.4]
chpasswd:
  list: |
    root:P@ssw0rd
    ubuntu:ubuntu
  expire: False
ssh_pwauth: True

